- name: Install and Configure containerd
  block:
    - name: Install containerd
      ansible.builtin.apt:
        name: containerd
        state: present

    - name: Create /etc/containerd
      ansible.builtin.file:
        state: directory
        path: /etc/containerd
        mode: '1777'

    - name: Initialize config
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      changed_when: true

    - name: Enable cgroup driver
      when: configurable.k8s.single_node
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: "            SystemdCgroup = false"
        replace: "            SystemdCgroup = true"

    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Ensure containerd is enabled and started
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: true

