# vim: set filetype=yaml.ansible :
---
- name: Join nodes to cluster
  block:
    - name: Apply join configuration template for nodes
      ansible.builtin.template:
        src: kubeadm-join-config.yaml.j2
        dest: /tmp/kubeadm-join.yaml
        mode: '1777'

    - name: Join nodes to cluster
      ansible.builtin.command: kubeadm join --config /tmp/kubeadm-join.yaml
      register: joined_node
      when: joined_node is not defined
      failed_when: "'ERROR' in joined_node.stderr"

  when: joined_node is not defined
