apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  subject:
    organizations:
      - hanapedia
  commonName: hanapedia.link
  dnsNames:
    - "*.hanapedia.link"
    - "hanapedia.link"
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-prod
