# vim: set filetype=yaml.ansible :
---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - "{{ config_path }}"
  roles:
    - kvm_apply
    - check_connections

- hosts: control_planes, nodes, loadbalancer
  name: Apply common setups to all vms
  become: true
  vars_files:
    - "{{ config_path }}"
  roles:
    - set_vm_facts
    - common_setup

- hosts: loadbalancer
  name: Setup loadbalancer vm
  become: true
  vars_files:
    - "{{ config_path }}"
  roles:
    - setup_lb

- hosts: control_planes, nodes
  name: Install Containerd and kube tools
  become: true
  vars_files:
    - "{{ config_path }}"
  roles:
    - install_cri
    - install_kube
