# vim: set filetype=yaml.ansible :
---
- name: Add docker credentials for kubelet
  hosts: control_planes, nodes
  become: true
  # vars_prompt:
  #   - name: username
  #     prompt: Docker Hub Username
  #   - name: password
  #     prompt: Docker Hub Password
  tasks:
    # - name: Docker login
    #   changed_when: true
    #   ansible.builtin.command:
    #     cmd: "docker login -u {{ username }} -p {{ password }}"

    - name: Create directory in the root path
      ansible.builtin.file:
        path: /.docker
        state: directory
        mode: '1777'

    - name: Copy docker credentials to root folder
      ansible.builtin.copy:
        src: /Users/hirokihanada/.docker/config.json
        dest: /.docker/
        mode: '1777'
