# vim: set filetype=yaml.ansible :
---
- name: Connect to cluster
  hosts: localhost
  tasks:
    - name: SSH port foreward
      changed_when: false
      vars:
        localport: "{{ item[1] }}"
        vm_hostname: "{{ k8s.cluster_name }}-{{ item[0] }}"
        vm_port: "{{ item[1] }}"
      ansible.builtin.command: "ssh -o ProxyCommand='ssh -W %h:%p -q {{ vm_host.domain }}' \
                                -fNL {{ localport }}:{{ vm_hostname }}.{{ libvirt.resources.network.domain }}:{{ vm_port }} \
                                {{ k8s.ubuntu.user }}@{{ vm_hostname }}.{{ libvirt.resources.network.domain }}"
      loop: # "{{ ['node1', 'loadbalancer'] | product(['32001', '6443']) | list }}"
        - "{{ ['loadbalancer', '6443'] }}"
        # - "{{ ['node3', '31300'] }}"
        # - "{{ ['node1', '31090'] }}"

    - name: Generate shell script
      ansible.builtin.template:
        src: ./templates/copy_kubectl_config.sh.j2
        dest: ./copy_kubectl_config.sh
        mode: '1777'

    - name: Copy kubectl context file
      ansible.builtin.command: bash ./copy_kubectl_config.sh
      changed_when: true

    - name: Add loadbalancer to etc hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{ k8s.cluster_name }}-loadbalancer.{{ libvirt.resources.network.domain }}"
