configurable:
  libvirt:
    # must be edited in sync with variables in libvirt ansible dir
    version: v1
    namespace: k8s

    network:
      domain: k8s.home
      network_cidr:
        - 192.168.100.0/24

  k8s:
    cluster_name: home-cluster
    single_node: false
    cni_plugin: flannel

    control_plane:
      cpu: 2
      mem: 4
      vms: 2
      disk: 16

    node:
      cpu: 2
      mem: 8
      vms: 3
      disk: 24
    
    loadbalancer:
      cpu: 1 
      mem: 4 
      vms: 1 
      disk: 8 

# vm host variables
vm_host:
  domain: HomeLan
  # domain: HomeWan
  user: hanapedia

# libvirt variables
libvirt:
  uri: "qemu+ssh://hanapedia@ubuntuhome/system"
  # non-kvm ubuntu image
  ubuntu_base_img_url: "https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
  # kvm variant with limited kernel
  # ubuntu_base_img_url: "https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img"
  #
# k8s varibales
k8s:
  version: '1.26'

  loadbalancer:
    setup: 
      packages:
        - haproxy
        - firewalld
        - network-manager
      services:
        - https
        - http 
      ports: 
        - "6443/tcp"

  ubuntu:
    user: ubuntu
    repo_key_dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    repo_file: /etc/apt/sources.list.d/kubernetes.list
    repo_key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    packages:
      - kubelet
      - kubeadm
      - kubectl



  network:
    network_cidr: 192.168.100.0/24
    service_cidr: 10.110.0.0/16
    pod_cidr: 10.20.0.0/16

  calico:
    calico_repo: https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/tigera-operator.yaml
    calico_operator: https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/tigera-operator.yaml
    calico_crd: https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/custom-resources.yaml

  flannel:
    flannel_repo: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

  cilium:
    chart:
      name: cilium
      ref: cilium/cilium
      url: https://helm.cilium.io/

ssh_keys: 
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCVDhT/P9zxI4ypW39uNYbkcl5kadudwPcJDdnCK1s5oURgNlmPpRtHP3l2Bfp2v4kd35PyQGXWA9xlK+oud5sILV04R1I0/lmr2p6HPO9lfhFuHxm+irXiJdkCdv9ymw7jrYSQPQy/Wv29pwSEVgha2OZnyUh7jsPw1XGVlv4ZjJxkYa/fRm2ERikz/2Qg7vCVRUoz8kAqVRgp+Ra5wR4WMY8XmF0b8vaucaV/vcCRV1w2/KQ9Vg5EHwkmZXRktSAiEMe/7a53ox4ADSY/hehR0bwEYBHcx93vUdOMztkQhW5AzJeqcbkc6jS0mBhU1HEmi1HFEVYP0sAGoIoQKrB/Un3hVt81B+xpZZVKFyoi7B56eZqEBfTf+bBlxWMpGcYjYO8AHzzT7tn7NM+0hvxATqdLGgt0/PryttW4W5FMKvJ+3t8VLO+RswwcDlgkPwIKkFLQV/ThXqBy7fZSL2hrlVN1xwLIgz8Z1mOaezHO+A+TQIkOjQG/jTx/f/aK4b9Pd0U2gyYMv7mKG+o84tSY0gU+geWtBhZKrg8r8iWGnhKJlYlZvISSUl1499svE1t1WSt4wOP+1B/LFJyk/1i9jXOfqYGiR5MHeBY6PXpjW/PkdSRudOIJ+4gkXdGIXTu41uIm5XLCIF5H9JHV6IgulurGia6Hp60omc6WG+gSUw== Hiroki macbook air"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMrBQUa4iADNPo3q/AQjpQyt1GFsdYKEW9Hd8kC478o3G4UbpuempbF/TlLixp/5tusMQjV9n/8kMJF1kj4lrsFHShftd7+ZXvUKkny8vEOF7aj79j3V9nYFPJ4NFIuJdzPsdfBG51DaT3wbossCEZshfNMc9iBISSLbSwDi6rwxCZX75GvQlMOR5TZSOXe7exj/28QSkyI9hcCbnbK0JG6Kabcxh1ZFAX/BwxDv/ywShWNbM2Y66KbO0BcjQjRPPgEIE05nW7C5Q0K5XJ5DAWHFzdACQakkRUuWXFrNS7ptZSIBY5BKryc0jq0JJinnmoAkMuEKCwUBIVa+5C4EokAM+ICTTaf6kWzWeraueZ4czFUdS5F7R6G/YNP6yTwmx2Y07lLt3m9EijxM8VTDgYsSS2R4yP8KGC1cof7W/Ia+8ZYdPR8Yg/QwfV+OP4CQELaIG1YvZldMJ1KUUsrkFNZ9cNbVtQIL2VLhw/P+PtOBlKgpESE+NvYDG7+3cImTk= hiroki11hanada@gmail.com"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYjW/93hLwUGJam0gJ5men/mLvd55egqUCkIN9xyH8Z9qbZd4eOAtto8JbaDqP5YN+Ct7besY3VJiH9MtG9fg0iEGZkWjRPQ7fFVEte532oY9YEdnJtvtwVfkQIXjsc+/BMmD/INei7nq0kUpmF3OtQ7VDeTJ/fE0SRv8HVRPeGH0Cp3tM6q/XgOPRcXgcKZhZD58aoXeCasaF9CuGNoIkTtVzoDlCrg5ooGiYo1OADfMxB5NtdWSwhASp8JvjnVddei7aD9gZTtrBnES90gUtZ2ocy/NVunGkPUILdrCbQw35p5LX327VE97Z6DqdlFKqwNQ1svTRQ1P5c8wK+sG9ykXYBM5VEyT0MIAqinYIUhuOlwA5pxmyscI8VCOjCGxviYG+Jy6ZvN6WujfijNUew839qMivR2COF/m5vM8v07HaySVsHgjC1xvVpkQK7Zj4Ybabr4+EJPuZKXnyq6tww9UHK7PkYzHZJUNn+cbb7r1jkhgoxptYwpMutDcxu/c= hirokihanada@Hirokis-MacBook-Air.local"
