# vim: set filetype=yaml.ansible :
---
- name: Apply calico plugin
  block:
    - name: Ensure that /tmp/{{ cluster_name }} exists
      ansible.builtin.file:
        path: /tmp/{{ k8s.cluster_name }}
        state: directory
        mode: '1777'

    - name: Download calico manifest
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.name }}"
        mode: '0644'
      loop:
        - name: /tmp/{{ k8s.cluster_name }}/calico-operator.yaml
          url: "{{ k8s.calico.calico_operator }}"
        - name: /tmp/{{ k8s.cluster_name }}/calico-crd.yaml
          url: "{{ k8s.calico.calico_crd }}"

    - name: Apply custom CIDR to calico installation manifest
      ansible.builtin.replace:
        path: /tmp/{{ k8s.cluster_name }}/calico-crd.yaml
        regexp: 192.168.0.0\/16
        replace: "{{ k8s.network.pod_cidr }}"

    - name: Temporary fix for non ascii char in Calico CRD (https://github.com/projectcalico/api/pull/46)
      ansible.builtin.replace:
        path: /tmp/{{ k8s.cluster_name }}/calico-operator.yaml
        regexp: \’
        replace: ""

    - name: Apply calico manifests to the cluster.
      kubernetes.core.k8s:
        state: present
        src: "{{ item }}"
        kubeconfig: /home/{{ vm_host.user }}/.kube/config
        wait: true
      loop:
        - /tmp/{{ k8s.cluster_name }}/calico-operator.yaml
        - /tmp/{{ k8s.cluster_name }}/calico-crd.yaml
  when: k8s.network.cni_plugin == 'calico'
