kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-data-pvc
  namespace: observability
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: observability
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      serviceAccount: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.26.0
        args:
        - '--storage.tsdb.retention=360h'
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/data'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: alertrules-volume
          mountPath: /etc/prometheus-rules
        - name: data-volume
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-configmap
      - name: alertrules-volume
        configMap:
          name: prometheus-alertrules
      - name: data-volume
        persistentVolumeClaim:
          claimName: prometheus-data-pvc
      nodeSelector:
        beta.kubernetes.io/os: linux
