# vim: set filetype=yaml.ansible :
---
- name: restart libvirt network and domains
  hosts: vm_host
  become: true
  tasks:
    # - name: restart network
    #   community.libvirt.virt_net:
    #     command: start
    #     name: "{{ k8s.cluster_name }}"

    - name: restart cp vms
      community.libvirt.virt:
        command: start
        name: cp{{ item }}
      with_sequence: "start=1 count={{ k8s.control_plane.vms }} format=%s"

    - name: restart node vms
      community.libvirt.virt:
        command: start
        name: node{{ item }}
      with_sequence: "start=1 count={{ k8s.node.vms }} format=%s"

    - name: restart loadbalancer vms
      community.libvirt.virt:
        command: start
        name: loadbalancer
