# vim: set filetype=yaml.ansible :
---
- name: Join control planes to the master cp
  block:
    - name: Apply join configuration template
      ansible.builtin.template:
        src: kubeadm-join-cp-config.yaml.j2
        dest: /tmp/kubeadm-join.yaml
        mode: '1777'

    - name: Join control planes
      ansible.builtin.command: kubeadm join --config /tmp/kubeadm-join.yaml
      register: cp_joined
      when: cp_joined is not defined
      failed_when: "'ERROR' in cp_joined.stderr"

  when: cp_joined is not defined
