# vim: set filetype=yaml.ansible :
---
- name: Apply terraform configuration
  community.general.terraform:
    project_path: '../terraform/'
    state: absent
  register: output

- name: Clear inventory file in terraform directory
  ansible.builtin.copy:
    src: '/dev/null'
    dest: '../terraform/inventory'
    mode: '0644'

- name: Clear inventory file in ansible directory
  ansible.builtin.copy:
    src: '/dev/null'
    dest: './inventory'
    mode: '0644'
