# vim: set filetype=yaml.ansible :
- name: Systemd-resolved setup on hosts
  block:
    - name: Ensure systemd-resolved config directory is present
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        mode: '1777'

    - name: Enable localdns if systemd-resolved is present
      ansible.builtin.template:
        src: systemd-resolved.j2
        dest: /etc/systemd/resolved.conf.d/{{ libvirt.namespace }}.conf
        mode: '1777'
      notify:
        - Restart systemd-resolved

- name: Ensure NetworkManager configuration directory exists
  ansible.builtin.file:
    path: /etc/NetworkManager/conf.d
    state: directory
    mode: '1777'

- name: Ensure NetworkManager dnsmasq directory exists
  ansible.builtin.file:
    path: /etc/NetworkManager/dnsmasq.d
    state: directory
    mode: '1777'

- name: Configure NetworkManager for local DNS
  ansible.builtin.copy:
    src: localdns.conf
    dest: /etc/NetworkManager/conf.d/{{ libvirt.namespace }}-localdns.conf
    mode: '1777'
  notify:
    - Restart NetworkManager

- name: Configure NetworkManager for libvirt network
  ansible.builtin.template:
    src: libvirt_dnsmasq.j2
    dest: /etc/NetworkManager/dnsmasq.d/{{ libvirt.namespace }}-libvirt_dnsmasq.conf
    mode: '1777'
  notify:
    - Restart NetworkManager
    - Wait for local DNS resolver to be up
