# vim: set filetype=yaml.ansible :
---
- name: Stop libvirt network and domains
  hosts: vm_host
  become: true
  tasks:
    - name: stop cp vms
      community.libvirt.virt:
        command: shutdown
        name: cp{{ item }}
      with_sequence: "start=1 count={{ k8s.control_plane.vms }} format=%s"

    - name: stop node vms
      community.libvirt.virt:
        command: shutdown
        name: node{{ item }}
      with_sequence: "start=1 count={{ k8s.node.vms }} format=%s"

    - name: stop loadbalancer vms
      community.libvirt.virt:
        command: shutdown
        name: loadbalancer

    # - name: stop network
    #   community.libvirt.virt_net:
    #     command: destroy
    #     name: "{{ k8s.cluster_name }}"
