# vim: set filetype=yaml.ansible :
---
- hosts: control_planes, nodes, loadbalancer
  name: Apply common setups to all vms
  become: true
  roles:
    - set_vm_facts
    - common_setup

- hosts: loadbalancer
  name: Setup loadbalancer vm
  become: true
  roles:
    - setup_lb

- hosts: control_planes, nodes
  name: Install Containerd and kube tools
  become: true
  roles:
    - install_cri
    - install_kube
