# vim: set filetype=yaml.ansible :
- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
    enabled: true

- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted

- name: Wait for local DNS resolver to be up
  ansible.builtin.wait_for:
    host: 127.0.0.53
    port: 53
    delay: 10
