version: '3'
services: 
  fanout-db:
    image: hiroki11hanada/tracing-example-app-fanout-db
    build:
      context: ./src/fanout-db
      dockerfile: ../mongo.Dockerfile
    ports:
      - 27017:27017


  fanout-1:
    image: hiroki11hanada/tracing-example-app-fanout-1
    build:
      context: ./src/fanout-1
      dockerfile: ../go.Dockerfile
    environment:
      LISTEN_PORT: 4000
      DB_ADDRESS: mongodb://fanout-db:27017
      DB_NAME: tracing-example-app
      COLLECTION_NAME: fanout1
    ports:
      - 4002:4000
    restart: always
    depends_on:
      - fanout-db

  fanout-2:
    image: hiroki11hanada/tracing-example-app-fanout-2
    build:
      context: ./src/fanout-2
      dockerfile: ../go.Dockerfile
    environment:
      LISTEN_PORT: 4000
      DB_ADDRESS: mongodb://fanout-db:27017
      DB_NAME: tracing-example-app
      COLLECTION_NAME: fanout2
    ports:
      - 4003:4000
    restart: always
    depends_on:
      - fanout-db

  fanout-3:
    image: hiroki11hanada/tracing-example-app-fanout-3
    build:
      context: ./src/fanout-3
      dockerfile: ../go.Dockerfile
    environment:
      LISTEN_PORT: 4000
      DB_ADDRESS: mongodb://fanout-db:27017
      DB_NAME: tracing-example-app
      COLLECTION_NAME: fanout3
    ports:
      - 4004:4000
    restart: always
    depends_on:
      - fanout-db

  fanout-4:
    image: hiroki11hanada/tracing-example-app-fanout-4
    build:
      context: ./src/fanout-4
      dockerfile: ../go.Dockerfile
    environment:
      LISTEN_PORT: 4000
      DB_ADDRESS: mongodb://fanout-db:27017
      DB_NAME: tracing-example-app
      COLLECTION_NAME: fanout4
    ports:
      - 4005:4000
    restart: always
    depends_on:
      - fanout-db

  fanout-5:
    image: hiroki11hanada/tracing-example-app-fanout-5
    build:
      context: ./src/fanout-5
      dockerfile: ../go.Dockerfile
    environment:
      LISTEN_PORT: 4000
      DB_ADDRESS: mongodb://fanout-db:27017
      DB_NAME: tracing-example-app
      COLLECTION_NAME: fanout5
    ports:
      - 4006:4000
    restart: always
    depends_on:
      - fanout-db

  gateway:
    image: hiroki11hanada/tracing-example-app-gateway
    build:
      context: ./src/gateway
      dockerfile: ../go.Dockerfile
    environment:
      LISTEN_PORT: 4000
      FANOUT_CLIENT_1_ADDRESS: fanout-1:4000
      FANOUT_CLIENT_2_ADDRESS: fanout-2:4000
      FANOUT_CLIENT_3_ADDRESS: fanout-3:4000
      FANOUT_CLIENT_4_ADDRESS: fanout-4:4000
      FANOUT_CLIENT_5_ADDRESS: fanout-5:4000
    ports:
      - 4000:4000
    restart: always
    depends_on: 
      - fanout-1
      - fanout-2
      - fanout-3
      - fanout-4
      - fanout-5

  loadgenerator:
    image: hiroki11hanada/tracing-example-app-loadgenerator
    build:
      context: ./src/loadgenerator
    environment:
      FRONTEND_ADDR: gateway:4000
      USERS: '10'
      HEADLESS: --headless
    depends_on:
      - gateway
