# vim: set filetype=yaml.ansible :
---
- name: Apply calico plugin
  when: configurable.k8s.cni_plugin == 'calico'
  block:
    - name: Ensure that /tmp/{{ cluster_name }} exists
      ansible.builtin.file:
        path: /tmp/{{ configurable.k8s.cluster_name }}
        state: directory
        mode: '1777'

    - name: Download calico manifest
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.name }}"
        mode: '0644'
      loop:
        - name: /tmp/{{ configurable.k8s.cluster_name }}/calico-operator.yaml
          url: "{{ k8s.calico.calico_operator }}"
        - name: /tmp/{{ configurable.k8s.cluster_name }}/calico-crd.yaml
          url: "{{ k8s.calico.calico_crd }}"

    - name: Apply custom CIDR to calico installation manifest
      ansible.builtin.replace:
        path: /tmp/{{ configurable.k8s.cluster_name }}/calico-crd.yaml
        regexp: 192.168.0.0\/16
        replace: "{{ k8s.network.pod_cidr }}"

    - name: Apply calico manifests to the cluster.
      kubernetes.core.k8s:
        state: present
        src: "{{ item }}"
        kubeconfig: /home/{{ vm_host.user }}/.kube/config
        wait: true
      loop:
        - /tmp/{{ configurable.k8s.cluster_name }}/calico-operator.yaml
        - /tmp/{{ configurable.k8s.cluster_name }}/calico-crd.yaml

- name: Configure Cilium
  when: configurable.k8s.cni_plugin == 'cilium'
  block:
    - name: Add helm chart repository for Cilium
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.repo_url }}"
      loop:
        - name: "{{ k8s.cilium.chart.name }}"
          repo_url: "{{ k8s.cilium.chart.url }}"

    - name: Ensure Cilium helm chart is installed
      kubernetes.core.helm:
        name: cilium
        chart_ref: "{{ k8s.cilium.chart.ref }}"
        kubeconfig: "/home/{{ vm_host.user }}/.kube/config"
        release_namespace: kube-system
        update_repo_cache: true
        values:
          ipam:
            mode: kubernetes
        wait: true

- name: Configure flannel
  when: configurable.k8s.cni_plugin == 'flannel'
  block:
    - name: Ensure that /tmp/{{ cluster_name }} exists
      ansible.builtin.file:
        path: /tmp/{{ configurable.k8s.cluster_name }}
        state: directory
        mode: '1777'

    - name: Download flannel manifest
      ansible.builtin.get_url:
        url: "{{ k8s.flannel.flannel_repo }}"
        dest: /tmp/{{ configurable.k8s.cluster_name }}/kube-flannel.yaml
        mode: 0755

    - name: Patch kube-flannel to use host-gw instead of vxlan
      ansible.builtin.replace:
        path: /tmp/{{ configurable.k8s.cluster_name }}/kube-flannel.yaml
        regexp: 'vxlan'
        replace: 'host-gw'

    - name: Apply flannel manifests to the cluster.
      kubernetes.core.k8s:
        state: present
        src: /tmp/{{ configurable.k8s.cluster_name }}/kube-flannel.yaml
        kubeconfig: "/home/{{ vm_host.user }}/.kube/config"
        wait: true
