# vim: set filetype=yaml.ansible :
- name: Prepare prerequisites
  block:
    - name: Add prerequisite modules to autostart
      ansible.builtin.blockinfile:
        path: /etc/modules-load.d/k8s.conf
        block: |
          overlay
          br_netfilter
        create: true
        mode: '1777'

    - name: Enable prerequisite modules
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - br_netfilter
        - overlay

    - name: Enable sysctl values
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: true
        sysctl_set: true
      loop:
        - key: net.ipv4.ip_forward
          value: 1
        - key: net.bridge.bridge-nf-call-ip6tables
          value: 1
        - key: net.bridge.bridge-nf-call-iptables
          value: 1

- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present

- name: Configure containerd
  block:
    - name: Create /etc/containerd
      ansible.builtin.file:
        state: directory
        path: /etc/containerd
        mode: '1777'

    - name: Initialize config
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      changed_when: true

    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Ensure containerd is enabled and started
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: true

- name: reboot cp and nodes
  ansible.builtin.reboot:
