# vim: set filetype=yaml.ansible :
---
- name: Apply terraform configuration
  community.general.terraform:
    project_path: '../terraform/libvirt_vms'
    state: present
    variables:
      libvirt_uri: "{{ libvirt.uri }}"
      domain: "{{ libvirt.network.domain }}"
      cluster_name: "{{ k8s.cluster_name }}"
      ubuntu_22_img_url: "{{ libvirt.ubuntu_base_img_url }}"
      ssh_keys: "{{ ssh_keys | to_json }}"
      num_control_plane: "{{ k8s.control_plane.vms }}"
      disk_size_cp: "{{ k8s.control_plane.disk }}"
      memory_cp: "{{ k8s.control_plane.mem }}"
      cpu_cp: "{{ k8s.control_plane.cpu }}"
      num_node: "{{ k8s.node.vms }}"
      disk_size_n: "{{ k8s.node.disk }}"
      memory_n: "{{ k8s.node.mem }}"
      cpu_n: "{{ k8s.node.cpu }}"
      disk_size_lb: "{{ k8s.loadbalancer.disk }}"
      memory_lb: "{{ k8s.loadbalancer.mem }}"
      cpu_lb: "{{ k8s.loadbalancer.cpu }}"
  register: output

# adding vms to inventory by their ip addresses
# - name: Copy inventory file to ansible
#   ansible.builtin.copy:
#     src: '../terraform/files/inventory'
#     dest: './files/inventory'
#     mode: '0644'

# Adding vms to inventory by their local domain name
# Deprecated since inventory generation is handled in another task
# control planes
# - name: Add control planes to given group
#   ansible.builtin.add_host:
#     hostname: "cp{{ item }}.{{ libvirt.network.domain }}"
#     ansible_user: ubuntu
#     ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q {{ vm_host.domain }}"'
#     groups:
#       - "control_planes"
#     group_children:
#       - "k8s_nodes"
#   loop: "{{ range(0, k8s.control_plane.vms) | list }}"
#   delegate_to: localhost
# # nodes
# - name: Add nodes to given group
#   ansible.builtin.add_host:
#     hostname: "node{{ item }}.{{ libvirt.network.domain }}"
#     ansible_user: ubuntu
#     ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q {{ vm_host.domain }}"'
#     groups:
#       - "nodes"
#     group_children:
#       - "k8s_nodes"
#   loop: "{{ range(0, k8s.node.vms) | list }}"
#   delegate_to: localhost
