# vim: set filetype=yaml.ansible :
---
- name: Apply terraform configuration
  community.general.terraform:
    project_path: "../terraform/libvirt-{{ libvirt.version }}"
    state: absent
    variables:
      libvirt_uri: "{{ libvirt.uri }}"
      version: "{{ libvirt.version }}"
      namespace: "{{ libvirt.namespace }}"
      domain: "{{ libvirt.network.domain }}"
      network_cidr: "{{ libvirt.network.network_cidr | to_json }}"
  register: output
