// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: pb-fanout-5/fanout.proto

package pb_fanout_5

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Fanout_5Client is the client API for Fanout_5 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Fanout_5Client interface {
	GetIds(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type fanout_5Client struct {
	cc grpc.ClientConnInterface
}

func NewFanout_5Client(cc grpc.ClientConnInterface) Fanout_5Client {
	return &fanout_5Client{cc}
}

func (c *fanout_5Client) GetIds(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/fanout_5.fanout_5/GetIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Fanout_5Server is the server API for Fanout_5 service.
// All implementations must embed UnimplementedFanout_5Server
// for forward compatibility
type Fanout_5Server interface {
	GetIds(context.Context, *Req) (*Res, error)
	mustEmbedUnimplementedFanout_5Server()
}

// UnimplementedFanout_5Server must be embedded to have forward compatible implementations.
type UnimplementedFanout_5Server struct {
}

func (UnimplementedFanout_5Server) GetIds(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIds not implemented")
}
func (UnimplementedFanout_5Server) mustEmbedUnimplementedFanout_5Server() {}

// UnsafeFanout_5Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Fanout_5Server will
// result in compilation errors.
type UnsafeFanout_5Server interface {
	mustEmbedUnimplementedFanout_5Server()
}

func RegisterFanout_5Server(s grpc.ServiceRegistrar, srv Fanout_5Server) {
	s.RegisterService(&Fanout_5_ServiceDesc, srv)
}

func _Fanout_5_GetIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fanout_5Server).GetIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fanout_5.fanout_5/GetIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fanout_5Server).GetIds(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Fanout_5_ServiceDesc is the grpc.ServiceDesc for Fanout_5 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fanout_5_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fanout_5.fanout_5",
	HandlerType: (*Fanout_5Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIds",
			Handler:    _Fanout_5_GetIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb-fanout-5/fanout.proto",
}
